### ISSUE TITLE
Github Action Usages

### ISSUE THREAD

**Issue by redisread** [redisread/something#4]

**Comment by redisread** [comment]
想要使用Github Action的首要条件是你有一个需要部署的项目，然后你需要编写一个.yml文件，该文件在仓库目录下 ` .github/workflows/*.yml `，名字可以任意，这就是第一步配置workflows.

**Comment by redisread** [comment]
这个文件用来规定自动化操作在什么时候触发启动，然后需要做哪些事情，比如下面这段代码就是一个workflows例子：
`name: Deploy on: push: branches: - master jobs: build: runs-on: ubuntu-latest steps: - name: Checkout master uses: actions/checkout@v2 with: ref: master - name: Setup node uses: actions/setup-node@v1 with: node-version: "10.x" - name: Build project run: yarn && yarn build - name: Upload COS uses: zkqiang/tencent-cos-action@master with: args: delete -r -f / && upload -r ./dist/ / secret_id: ${{ secrets.SECRET_ID }} secret_key: ${{ secrets.SECRET_KEY }} bucket: ${{ secrets.BUCKET }} region: ap-shanghai`

**Comment by redisread** [comment]
```
name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Build project
        run: yarn && yarn build

      - name: Upload COS
        uses: zkqiang/tencent-cos-action@master
        with:
          args: delete -r -f / && upload -r ./dist/ /
          secret_id: ${{ secrets.SECRET_ID }}
          secret_key: ${{ secrets.SECRET_KEY }}
          bucket: ${{ secrets.BUCKET }}
          region: ap-shanghai
```
